Add a proper top and bottom layout
ocaml-flambda/flambda-backend pull request #1158
Opened 2023-03-01 11:19 UTC by Ekdohibs

This is extracted from Pierre's PR with test layouts. Note that for now, `layout_top` is defined as `layout_any_value` and not `Ptop`: otherwise, three tests fail, related to dissect-let-rec and regions.

There is a question as to whether we want to add `Ptop` in the first place, or if this PR should only add `Pbottom` (which is needed, because in some places we really need a `Pbottom` compatible with all layouts).

2023-03-01 17:05 UTC, chambart commented
So right now layout top is not required, but this is supposed to be the result of `layout_union` between incompatible layouts.
But it is not obvious whether we want to fail directly during `layout_union` or propagate it to later. Both have their advantages as debugging options.

2023-03-02 09:39 UTC, mshinwell requested changes

2023-03-02 09:39 UTC, mshinwell commented on backend/cmmgen.ml
> +    let _cbody = transl_body env in
This should have a type annotation, just in case extra parameters are added to transl_body later...

2023-03-02 09:39 UTC, mshinwell commented on ocaml/lambda/lambda.ml
> +let layout_top = layout_any_value
Let's leave a CR here in case this gets merged before Dissect_letrec is fixed

2023-03-02 09:39 UTC, mshinwell commented on backend/cmm_helpers.ml
> +  | Ptop | Pbottom -> Misc.fatal_error "No machtype for layout"
Let's use Misc.fatal_errorf and print which layout is at fault

2023-03-02 09:39 UTC, mshinwell commented on middle_end/flambda/closure_offsets.ml
> +          Misc.fatal_error "Wrong layout in closure"
Let's use Misc.fatal_errorf again here

2023-03-02 10:42 UTC, mshinwell approved these changes

2023-03-02 11:23 UTC, merged