Unboxed numbers
ocaml-flambda/flambda-backend pull request #1165
Opened 2023-03-02 14:22 UTC by Ekdohibs

This adds boxing and unboxing primitives for all boxed integers, as well as floats. This pull request does not however include frontend access to these, as it is unsafe: for this, see the pull request XXX.

2023-03-02 15:01 UTC, mshinwell commented
I'll review this

2023-03-09 09:14 UTC, mshinwell requested changes

2023-03-09 09:14 UTC, mshinwell commented on middle_end/flambda2/from_lambda/lambda_to_flambda_primitives.ml
> +    let kind =
That said, why don't you move this conversion into `Flambda_kind.Boxable_number`?  It's duplicated below at the moment.

2023-03-09 09:14 UTC, mshinwell commented on middle_end/flambda/flambda_to_clambda.ml
> +      end;
Typo, and you can just use `Misc.fatal_errorf`.

2023-03-09 09:14 UTC, mshinwell commented on middle_end/clambda_primitives.ml
> +  | Punbox_float -> Lambda.Punboxed_float
This is missing a case for unboxing ints, no?

2023-03-09 12:04 UTC, Ekdohibs commented on middle_end/flambda2/from_lambda/lambda_to_flambda_primitives.ml
> +    let kind =
Actually the function already existed in the file, using it now.

2023-03-09 12:08 UTC, Ekdohibs commented on backend/cmmgen.ml
> +          | Punboxed_int Pint64 -> typ_int64
I think both are the same on 64-bit architectures, but it seemed safer this way.

2023-03-10 08:58 UTC, mshinwell requested changes

2023-03-10 08:58 UTC, mshinwell commented on middle_end/flambda/flambda_to_clambda.ml
> +        Misc.fatal_errorf "Imcompatible layouts:@.body: %a@.function: %a@.%a@."
Imcompatible -> Incompatible

2023-03-10 09:01 UTC, Ekdohibs commented on middle_end/flambda/flambda_to_clambda.ml
> +        Misc.fatal_errorf "Imcompatible layouts:@.body: %a@.function: %a@.%a@."
```suggestion
        Misc.fatal_errorf "Incompatible layouts:@.body: %a@.function: %a@.%a@."
```

2023-03-10 09:04 UTC, mshinwell approved these changes

2023-03-10 10:57 UTC, merged