Install AFL packages on CI workers
ocaml-flambda/flambda-backend pull request #1197
Opened 2023-03-10 15:08 UTC by mshinwell

This should now cause the AFL tests in the testsuite to fail (until PR1196 is merged) rather than being skipped.

2023-03-10 15:27 UTC, Gbury requested changes

2023-03-10 15:27 UTC, Gbury commented on .github/workflows/build.yml
> +      if: matrix.os != 'macos-latest'
```suggestion
      if: matrix.os == 'ubuntu-latest'
```

The not-equal test seems a bit brittle if/when we try and test flamdba2 on windows (which should happen eventually).

2023-03-10 15:37 UTC, Gbury approved these changes

2023-09-21 16:57 UTC, mshinwell commented
I've rebased this, hopefully it will now work following @ncik-roberts 's fixes

2023-09-22 10:06 UTC, merged