Add debug option for flambda2
ocaml-flambda/flambda-backend pull request #1252
Opened 2023-03-23 17:24 UTC by Gbury

This PR adds a debug option for flambda2. This option can be used either via a CLI flag `-flamdba2-debug` or via en env variable `FLAMBDA2_DEBUG`.

Currently, setting this to `true` only gives unique names to every continuation, which makes it a lot easier to follow what happens to which continuation.

Additionally, `Simplify_import` now defines the `debug ()` function, that can be used in code to add debugging statements such as `if debug () then Format.eprintf ....`, which happens quite a lot in my experience.

2023-03-24 10:25 UTC, mshinwell requested changes

2023-03-24 10:25 UTC, mshinwell commented on driver/flambda_backend_flags.ml
> +      match Sys.getenv "FLAMBDA2_DEBUG" with
Hmm, I'd rather not have the compiler read more environment variables.  You should be able to arrange for this to work via `OCAMLPARAM` I think?

2023-03-24 10:25 UTC, mshinwell commented on driver/flambda_backend_args.ml
> +  "-no-flambda2-debug", Arg.Unit f, " Disable debug ouput for the flambda2 pass"
Inconsistent capitalisation of flambda2

2023-03-29 13:17 UTC, Gbury commented on driver/flambda_backend_args.ml
> +  "-no-flambda2-debug", Arg.Unit f, " Disable debug ouput for the flambda2 pass"
fixed

2023-03-29 13:18 UTC, Gbury commented
@mshinwell comments have been addressed, this is ready for another review

2023-03-29 13:26 UTC, mshinwell approved these changes

2023-04-03 12:26 UTC, merged