Backend changes for multiple returns
ocaml-flambda/flambda-backend pull request #1268
Opened 2023-03-29 12:52 UTC by lthls

Extracted from #1248.
Two changes are not strictly necessary:
- The patch to `spill.ml` is just an unrelated bug fix that I made while debugging the code.
- The addition of `Cmm_helpers.make_tuple` is useful for generating Cmm code with multiple returns, but could be kept as part of the middle-end patches instead.

I chose to integrate them anyway because it was simpler to extract everything in the `backend/` folder, and they're short and easy to review.

I haven't backported those changes to the `ocaml/` directory, I couls probably do it as part of this PR too.

2023-04-05 13:02 UTC, Gbury approved these changes

2023-04-10 15:21 UTC, gretay-js approved these changes
The changes in various `Proc`, `Cmm_helpers` and `Selectgen` all look fine to me. As far as I can see, the generated code will be the same as before for functions with a single return.

Do we expect to use unboxed types in the compiler itself? If not, I'd rather not make these changes to code generation `ocaml/asmcomp` directory, unless of course we need them for `ocaml-jst`.

@xclerc can you please confirm that the change in validator test is correct? I don't understand this test enough to be sure that it needs  `Proc.loc_results_return` everywhere or `Proc.loc_results_call`.

The fix for `spill.ml` : I would prefer to put it into a separate PR. This bug might cause miscompilation, unless `Iexit` labels are not unique across different functions in the same compilation unit or somehow the spill instructions it returns are ignorexd. Wonder why we have never noticed this bug in the generated code.

2023-04-10 15:27 UTC, mshinwell commented
We've ported all of the middle-end layout changes to `ocaml/` so I think we should probably do the same as this one, then `ocaml-jst` will be in a fully working state.  Agreed that the fix to `Spill` should be in a separate PR.

2023-04-10 15:35 UTC, gretay-js requested changes
- split out the bug fix in spill
- port proc changes to asmcomp

2023-04-10 15:38 UTC, xclerc commented
> @xclerc can you please confirm that the change in validator test is correct? I don't understand this test enough to be sure that it needs `Proc.loc_results_return` everywhere or `Proc.loc_results_call`.

The change look correct to me, but I
am a bit worried it is not tested.

2023-04-11 10:12 UTC, lthls commented
I've split out the spill change (will submit a separate PR later), and ported the changes to the `ocaml/` folder, including all supported architectures.
I get an error for `riscv` when running `make check_all_arches`, but it seems unrelated to this PR. All the other architectures build correctly.

2023-04-11 17:09 UTC, merged