Prepare translation of primitives in lambda_to_flambda to unboxed products
ocaml-flambda/flambda-backend pull request #1465
Opened 2023-06-08 16:13 UTC by Ekdohibs

The translation now takes a list of list of simples to represent the arguments (for now, all the inner lists have length one since there are no unboxed products), and returns a list of bindings. This also includes some changes in the handling of `Praise` that were in #1382.

2023-06-08 16:15 UTC, mshinwell commented
I will review this.

2023-06-14 10:16 UTC, mshinwell requested changes
A few minor things

2023-06-14 10:18 UTC, Ekdohibs commented on middle_end/flambda2/from_lambda/closure_conversion.ml
> +    let args = List.flatten args in
I'm thinking that if there are unboxed products, they will just be given as successive parameters to the C call (assuming we get C calls taking unboxed products at some point). However, if you think it's best to add a check, I can do that.

2023-06-14 11:12 UTC, mshinwell approved these changes

2023-06-14 12:31 UTC, merged