Propagate builtin, effects, and coeffects from Primitive to Cextcall
ocaml-flambda/flambda-backend pull request #15
Opened 2021-04-27 13:45 UTC by gretay-js

on top of #11 and #10, only the top commit is new.

2021-04-28 12:32 UTC, gretay-js commented
Splitting up effects and coeffects into a separate PR.

2021-04-29 14:38 UTC, mshinwell requested changes

2021-04-29 14:38 UTC, mshinwell commented on backend/cmm_helpers.mli
> +(** [transl_cextcall prim args dbg type_of_result] returns Cextcall operation
transl_cextcall -> cextcall

2021-04-29 14:38 UTC, mshinwell commented on backend/cmm_helpers.mli
> +    that corresponds to [prim]. If [prim] is a builtin supported on the target,
maybe "builtin" -> "C builtin" to clarify

2021-04-29 15:38 UTC, gretay-js commented
I fixed the comment, thanks!  
Squashed the commits.

2021-04-29 16:31 UTC, mshinwell approved these changes

2021-04-29 16:31 UTC, merged