[Internal assembler] Emit all sections as before but debug_line and debug_frames which are delayed
ocaml-flambda/flambda-backend pull request #1719
Opened 2023-08-10 09:03 UTC by poechsel

#1643 caused problem with mdx as it's involved a big changed in signatures.

This PR does the same but explicitly. All sections - but .debug_line, and later .debug_frames are emitted directly. .debug_line and .debug_frames are now considered as "delayed" and will only be emitted once [Dwarf.emit_delayed] is called.

2023-08-10 15:25 UTC, mshinwell commented
I'm reviewing this

2023-08-11 08:51 UTC, mshinwell requested changes

2023-08-11 08:51 UTC, mshinwell commented on backend/asm_targets/asm_section.mli
> +(* If [is_delayed] = true the corresponding function will be emitted after
This should say "section"

2023-08-11 08:51 UTC, mshinwell commented on backend/internal_assembler/internal_assembler.ml
> +                sec_instrs = Array.of_list instructions
The useful comment that was here appears to have been lost?

2023-08-11 08:51 UTC, mshinwell commented on backend/debug/dwarf/dwarf_ocaml/dwarf.ml
> +      "Cannot call [Dwarf.emit] more than once on a given value of type \
This should say Dwarf.emit_delayed

2023-08-11 08:51 UTC, mshinwell commented on backend/x86_proc.ml
> +  (* Section_name.Tbl.clear delayed_sections; *)
Is this needed?  If not let's delete the line.

2023-08-11 14:28 UTC, mshinwell approved these changes

2023-08-11 14:50 UTC, xclerc approved these changes

2023-08-11 15:10 UTC, merged