Drop equations involving foreign variables only
ocaml-flambda/flambda-backend pull request #185
Opened 2021-08-20 16:54 UTC by lthls

See the comment added to `Typing_env.add_equation` for details.

Note that the use of an exception is a hack to avoid re-indenting significant amounts of code. I can switch it to a less hackish patch after reviews.

Preliminary tests on the `nocrypto` package show that it fixes the `disjoint_map` error when loading packs.

2021-08-23 09:23 UTC, mshinwell requested changes

2021-08-23 09:23 UTC, mshinwell commented on middle_end/flambda2/basic/name.ml
> +let is_foreign t =
Can we use "imported" rather than "foreign" to be consistent with elsewhere?

2021-08-23 09:23 UTC, mshinwell commented on middle_end/flambda2/types/env/typing_env.rec.ml
> +         A foreign variable can't alias to a non-foreign symbol either, but
Maybe insert some brief text here giving the reason why this can't currently happen (imported variable aliased to non-imported symbol).

2021-08-23 09:23 UTC, mshinwell commented on middle_end/flambda2/types/env/typing_env.rec.ml
> +         equality primitive), it's impossible to reach this case in practice.
Could you please add a comment in the phys-equal simplification code as to the things we need to watch out for when implementing that properly?  I remember there was a patch fairly recently that would also have required modification if such an implementation existed, but I can't recall exactly what it was.

2021-08-23 14:22 UTC, lthls commented
I think I've missed a case:
```ocaml
match Imported.foo with
| None -> ()
| Some _ -> assert false
```
Here we could introduce an equation `Imported.foo/XXX : (= 0)`, which would put an imported variable in the keys of the aliases.
More importantly, the calls to `add_equation` would not trigger this check, as we would add `*match*/XXX : (= Imported.foo/XXX)` then `*match*/XXX : (= 0)`.

This is likely infrequent, but should be fixed too.
The problem with this case is that it cannot be detected in Typing_env, it must be handled in Aliases directly.
I'll try to see if I can make a fix there (it will likely replace this one).

2021-08-23 15:41 UTC, mshinwell commented
Would writing a full merge function in `Aliases` be sufficient to deal with this (and is it something we will need when dealing with a proper `phys_equal` implementation)?  If so maybe we should go ahead with that now.

2021-08-23 16:47 UTC, lthls commented
A proper `phys_equal` implementation would only make the problems more common. Writing a full merge function is one possible way do deal with the problem, but I'm trying an approach where those extra equations are removed when we "seal" the Aliases structure for exporting (in the sense that after exporting an environment, it is never modified again, so we could allow ourselves to break some invariants). It seems to be mostly working, but I need to tweak the invariant checks a bit.

2021-09-01 18:01 UTC, lukemaurer reviewed
Just to check my understanding: We do risk (safely) dropping useful information here, correct? Just only in rare cases?

2021-09-02 13:58 UTC, lthls commented
> Just to check my understanding: We do risk (safely) dropping useful information here, correct? Just only in rare cases?

Yes and no. We could end up dropping useful information, but given the way we lookup information on imported variables, we couldn't have accessed the extra information.

Example:
```ocaml
(* foo.ml *)
let foo = Sys.opaque_identity true

(* bar.ml *)
match Foo.foo with
| true ->()
| false -> assert false
```
At the end of `Bar`, when emitting the cmx, we know that `Foo.foo` is an alias to the tagged constant 1.
However, even if we stored this information in `bar.cmx`, when a third module accesses `Foo.foo` then the canonical alias will be looked up in `foo.cmx` so it will not be possible to access the extra information from `Bar`, even if we've already loaded its cmx.


To solve the issue of the broken invariant, I could propose a more radical solution: use a different type for exported aliases than the regular type. The exported aliases only need the `canonical_elements` map.
In practice this could involve either a variant type (`Current of t | Exported of { canonical_elements: ... }`), some GADT magic, or something more systematic (for example we don't really need imported typing envs to have the same type as regular environments, but we risk some code duplication if we split the types).

As a quick fix we could systematically reset the fields other than `canonical_elements` to empty maps on export. I think `get_canonical_element_exn` already does the right thing in this case.

2021-09-03 12:23 UTC, lthls commented
As discussed, I've implemented the "quick fix" from my previous comment: only the `canonical_elements` map is preserved for export.
The code of the `merge` function can then be greatly simplified (though I've left a few sanity checks just in case).

2021-09-03 13:37 UTC, lukemaurer approved these changes

2021-09-03 14:36 UTC, mshinwell approved these changes

2021-09-03 15:33 UTC, merged