Remove misleading comment
ocaml-flambda/flambda-backend pull request #199
Opened 2021-09-01 12:52 UTC by xclerc

This pull request simply deletes a comment which happens
to be inconsistent with the code in another module.
Precisely, `Tailcall (Self _)` does not raise (See [here](https://github.com/ocaml-flambda/flambda-backend/blob/main/backend/cfg/linear_to_cfg.ml#L212)).

2021-09-01 13:34 UTC, gretay-js requested changes
While reviewing this change, I've noticed that `Mach.operation_can_raise` returns `false` for all tailcall operations, but `Linear_to_cfg.can_raise_terminator` returns true for Tailcall (Func). We should probably keep it consistent between Mach and Linear_to_Cfg, although I am not sure which one is correct. 
This is related to recent changes and in particular this comment: https://github.com/ocaml/ocaml/pull/10354/files#r616407258

2021-09-01 13:34 UTC, gretay-js commented on backend/cfg/eliminate_fallthrough_blocks.ml
>      || block.can_raise
It is safe to remove the disjunct `block.can_raise`  that the comment was referring to.

2021-09-14 09:13 UTC, mshinwell commented
Can we try to get this PR fixed and merged?

2021-09-14 09:40 UTC, gretay-js approved these changes

2021-09-29 08:21 UTC, mshinwell commented
@xclerc Can we try to get this PR merged please?

2021-09-29 08:46 UTC, xclerc commented
I think I have pushed the changes requested by @gretay-js.

2021-09-29 09:00 UTC, gretay-js commented
> I think I have pushed the changes requested by @gretay-js.

thanks! it just needs a rebase.

2021-09-29 10:02 UTC, merged