Replace unused raise argument with a dummy value
ocaml-flambda/flambda-backend pull request #200
Opened 2021-09-02 13:16 UTC by chambart

When compiling with `-g`
```OCaml
   try assert (0 = 40 + 2) with _ -> ()
```
the exception handler is kept, but the exception symbol is marked as unused by `Data_flow` because the exception value is actually unused. But we can't remove the argument because exceptions arguments can't be removed.

2021-09-02 15:37 UTC, Gbury requested changes
There is a typo (see comment), but otherwise this looks good.
Is possible, could you add your example as a regression test in the testsuite ?

2021-09-02 15:37 UTC, Gbury commented on middle_end/flambda2/simplify/simplify_let_cont_expr.ml
> +                 the moment represent cannot represents this transformation, so
```suggestion
                 the moment represent this transformation, so
```

2021-09-02 15:37 UTC, Gbury commented on middle_end/flambda2/simplify/simplify_apply_cont_expr.ml
> +          | first_arg :: other_args ->
Maybe we this should be named something like `exn_arg` or `exn_bucket` to explicit the fact that it is the exception being raised ?

2021-09-02 15:39 UTC, mshinwell commented
Please don't merge this until after I've merged a forthcoming patch that significantly rearranges some of the code in the simplifier, in preparation for ocamlformat.

2021-09-09 13:43 UTC, Gbury approved these changes

2021-09-14 13:27 UTC, lthls approved these changes

2021-09-14 13:29 UTC, merged