Stack check as a linear/CFG instruction
ocaml-flambda/flambda-backend pull request #2372
Opened 2024-03-19 09:32 UTC by xclerc

This pull request gives an explicit representation
to stack checks on the linear and CFG IRs. The
semantics is unaffected. This change is only a
preliminary step to be able to control where
the check is emitted, rather than always emit it
at the top of a function.

2024-04-05 17:03 UTC, mshinwell requested changes
Looks good, just minor comments.

2024-04-05 17:03 UTC, mshinwell commented on backend/amd64/stack_check.ml
> +   (* CR mshinwell: this should be conditionalized on a specific
I think this CR is irrelevant now and can be deleted

2024-04-05 17:03 UTC, mshinwell commented on backend/amd64/stack_check.ml
> +            ~available_across:None
Let's try to set these availability values correctly (presumably based on the first instruction of `fundecl.fun_body`?)

2024-04-05 17:03 UTC, mshinwell commented on backend/amd64/emit.mlp
> +  | None -> ();
Spurious semicolon

2024-04-05 17:03 UTC, mshinwell commented on backend/amd64/emit.mlp
> +  sc_max_frame_size : int; (* Size for reallocation. *)
maybe put "in bytes" here

2024-04-11 14:05 UTC, xclerc commented on backend/cfg/cfg_intf.ml
> +          save_registers : bool
Indeed, `save_registers` is simply "not the first instruction".

2024-04-12 09:34 UTC, mshinwell approved these changes

2024-04-12 10:07 UTC, merged