Inline variable definitions into let-symbol expressions
ocaml-flambda/flambda-backend pull request #251
Opened 2021-09-13 17:36 UTC by mshinwell

I think there's been a longstanding problem with Flambda 2 causing excessive numbers of live variables for compilation of let-symbol expressions corresponding to large module blocks.  This causes poor compilation time when using the default register allocator; with the linear scan allocator, register allocation may succeed but the "number of live variables" field in the frame table may overflow (cf. #246).

@lukemaurer is digging out some recent examples but I think the major problem might be when the contents of lots of module fields are copied, when such fields are not known to hold symbols.  There are two such examples (one using `include` and the other using a functor) in the test case here.  (The `.mli` is just to control unwanted bindings in the output.)

This PR attempts to solve this problem by using the existing `Un_cps` code that sinks let-bindings down and substitutes ones that are used exactly once (which I suspect the majority of the variables holding copied values will be).  I looked through the `Un_cps` code to see if I could find anything wrong with using the variable-inlining code at let-symbol bindings, but it did seem ok.

The Cmm code for the test cases here used to be compiled as:
```
(function camlTest__entry ()
 (catch
   (let
     ; In a large example each of the following four bound variables could be
     ; held live for a long time, with significant interference with other variables.
     (b159/275 (load val (+a "camlStdlib__Sys" 24))
      include180/292
        (app{test.ml:14,8-52} "camlTest__anon-fn[test.ml:9,9--87]_0_3_code"
          "camlTest__Pmakeblock87" val)
      Pfield181/293 (load val (+a include180/292 8))
      Pfield182/294 (load val include180/292))
     (store val(root-init) (+a "camlTest" 8) b159/275)
     (store val(root-init) (+a "camlTest" 24) Pfield182/294)
     (store val(root-init) (+a "camlTest" 32) Pfield181/293)
     (exit 1 "camlTest"))
 with(1 *ret*158/274: val) 1))
```
whereas now we get:
```
(function camlTest__entry ()
 (catch
   (let
     include180/292
       (app{test.ml:14,8-52} "camlTest__anon-fn[test.ml:9,9--87]_0_3_code"
         "camlTest__Pmakeblock87" val)
     (store val(root-init) (+a "camlTest" 8)
       (load val (+a "camlStdlib__Sys" 24)))
     (store val(root-init) (+a "camlTest" 24) (load val include180/292))
     (store val(root-init) (+a "camlTest" 32)
       (load val (+a include180/292 8)))
     (exit 1 "camlTest"))
 with(1 *ret*158/274: val) 1))
```
The variable corresponding to the applied functor is still potentially live for a long time, but I think that's unavoidable, at least until we have function return type inference in the simplifier.  (At that point projections from the applied functor may well be able to be simplified to symbols.)

2021-09-13 18:36 UTC, Gbury commented
I agree that we should solve the problem, but there's a bug currently: in your example, the load `(b159/275 (load val (+a "camlStdlib__Sys" 24))` has from being executed before the call to the anonymous function, to being executed after the function call with your patch. Even if in this particular case, it's probably correct, it still remains that your patch allowed a co-effectful expression (the load) to be re-ordered through an effectful expression (the function call), which generally is incorrect. I'll investigate a bit more to find out why this is happening.

2021-09-13 19:09 UTC, lthls commented
> it still remains that your patch allowed a co-effectful expression (the load) to be re-ordered through an effectful expression (the function call), which generally is incorrect.

I would consider a load operation to have co-effects only if it is a mutable load. We should still have enough mutability information in `Un_cps` to make the distinction. In particular, loads from symbols should always be immutable because we don't generate mutable symbols. (However, that only works if we have correctly scoped bindings and don't move symbol loads before the initialisation code of the corresponding symbol. Loads from imported symbols are guaranteed to be fine, but for the current compilation unit we may need to be careful).

2021-09-15 14:59 UTC, mshinwell commented
I looked at an example in the JS tree which was still causing trouble even after the first commit on this PR.  The problem was that some loads weren't being sunk down far enough.  In this particular case I think the problem is that the corresponding let-bindings were being placed as a result of the flushing prior to new let-symbol declarations.  However the general problem here seems to be that `Un_cps` is too eager about flushing pure let bindings.  My understanding is that the flushing function should never need to make bindings for the `pures` where the `inline` flag is set, since they will always be substituted.  The second commit here does this; inlinable pure bindings are never flushed.  This has solved the problem on the example and the code now looks good.  Register allocation now runs in a reasonable time (about 3 seconds, it was more than an order of magnitude worse before; with the linear scan allocator it's now under a second).

I am concerned that when we go via the new classic mode path, bypassing the simplifier, that we're going to have problems in this area again.  We aren't going to be able to simplify the output of `Translmod` and I worry this is going to leave us in the position the compiler was presumably in originally, prior to the "`transl_store`" functions having been written.  However, with luck, using the linear scan register allocator will help here.  I suspect `-Oclassic` is going to have to imply `-linscan`, at least until large numbers of interferences cause fewer complexity problems in the normal register allocator.

2021-09-15 15:51 UTC, Gbury commented
> My understanding is that the flushing function should never need to make bindings for the `pures` where the `inline` flag is set, since they will always be substituted.

Well, the actually, they should not always be substituted, because sometimes substituting them can make the expression cross a loop boundary, in which case the pure expression will be computed for each iteration of a loop, instead of once before the loop.

For instance, consider the following program:
```ocaml
let f n =
  let m = n + n in
  for i = 0 to n do
    print_int (i + m)
  done
```
With your patch, the computation of `m` is inlined inside of the loop. While in this particular case, it's likely not disastrous, this patch makes it so that any pure computation (regardless of size) bound to a variable that is syntactically used only once in a loop, will be inlined inside the loop, and thus the computation of the expression will be done for each iteration of the loop instead of once before the loop.

Basically, there are two main reasons why we have this problem:
- the criterion used to decide whether to inline or not is based on the syntactic number of occurrences, whereas ideally it'd be based on the semantic number of expected execution of the expression. So that means that at the declaration of a variable, we can decide to inline it, but later realize that we do not actually want to inline it.
- there are two different reasons for flushing the environment:
  + at a point where control flow can branch, we flush because we don't know on which path of the control flow the delayed let-bindings should be placed (later, we might instead try and split the env according to which variables appear in which branch, but considering the potential dependencies between variables, this might be complex to do properly)
  + before entering a recursive continuation, we also flush, to ensure that nothing defined outside a recursive continuation will get inlined inside the recursive continuation

Your statement that pure computations should always be inlined (and thus not flushed), is only correct when the syntactic occurrence criterion agrees with the actual semantic criterion (i.e. when the syntactic number of occurrences is the same as the number of evaluation of the expressions at runtime).

I see mainly two ways to keep your change and stay correct:
- maybe we could envision to store more information in the name occurrences to distinguish the problematic cases, but it would likely require a large number of changes (and tests).
- or we need to distinct flush operations (or an argument to the flush function), to distinguish the two types of reasons for flushing (as described above).

2021-09-15 15:52 UTC, Gbury requested changes
(see my comment above)

2021-09-15 15:55 UTC, mshinwell commented
I'm not convinced there's necessarily a problem here.  These pure computations seem likely to be small.  Given this, it might even be better to inline them into loops, since it will probably lower register pressure for the whole loop.  It's not as if an allocation is being moved into a loop.

2021-09-15 15:58 UTC, Gbury commented
Well, that's because currently, there aren't that many pure expressions, but imagine that at one point, we manage to correctly identify some function calls as pure, e.g. `Array.length`, or even a function call where we have computed and stored in the approximation of the function that the function is pure (let's say a recursive function that compute fibonacci), then we'll have some real problems.

2021-09-15 16:05 UTC, lthls commented
I thought that only let-bindings end up in this environment ? If that's the case, then we don't have to worry too much: we could end up with an arbitrarily large expression, by combining primitives, but we will never end up with a function call.

2021-09-15 16:10 UTC, Gbury commented
> I thought that only let-bindings end up in this environment ? If that's the case, then we don't have to worry too much: we could end up with an arbitrarily large expression, by combining primitives, but we will never end up with a function call.

Actually, function calls whose return continuation is inlined (and that's most of function calls I expect) will be treated as let-bindings (this allows to e.g. inline a pure computation across a function call, which is necessary for the original example in this PR to work, since the firs tload has to be inlined/substituted across the function call introduced by the `Sys.os_type`).

2021-09-16 14:11 UTC, Gbury approved these changes

2021-09-16 14:34 UTC, merged