Fix conflicts in Unix library stubs
ocaml-flambda/flambda-backend pull request #2814
Opened 2024-07-18 11:28 UTC by mshinwell

As subject

2024-08-06 13:07 UTC, stedolan requested changes

2024-08-06 13:07 UTC, stedolan commented on ocaml/otherlibs/unix/signals.c
>  #else
The comment is obsolete now

2024-08-07 16:51 UTC, mshinwell commented on ocaml/otherlibs/unix/signals.c
>  #else
Fixed, please approve

2024-08-12 13:56 UTC, stedolan approved these changes

2024-08-12 14:05 UTC, merged