Add compiler warning for inferred tailcalls in TCO'd cycles
ocaml-flambda/flambda-backend pull request #2877
Opened 2024-07-31 18:39 UTC by tylerhou

TODO

2024-08-08 19:34 UTC, dvulakh requested changes
Looks good overall! Left a few comments.

2024-08-08 19:34 UTC, dvulakh commented on backend/asmgen.ml
> +          (*      Analyze_tailcall_graph.fixup_inlined_tailcalls) *)
Let's return this.

2024-08-08 19:48 UTC, tylerhou commented on backend/analyze_tailcall_graph.ml
> +      adjacencies_with_loc : Edge.with_loc Vertex.Tbl.t
Done.

2024-08-08 19:48 UTC, tylerhou commented on backend/analyze_tailcall_graph.ml
> +            | Tail_position _, false ->
Done.

2024-08-08 19:48 UTC, tylerhou commented on backend/asmgen.ml
> +          (*      Analyze_tailcall_graph.fixup_inlined_tailcalls) *)
Done.

2024-08-09 14:28 UTC, dvulakh approved these changes
Looks good, thanks!

2024-08-09 17:00 UTC, merged