Remove Lambda.alloc_mode from backend/
ocaml-flambda/flambda-backend pull request #3056
Opened 2024-09-20 21:01 UTC by anfelor

This PR separates the definition of `alloc_mode` in Lambda from uses in the backend as discussed this morning with @mshinwell and @goldfirere. In defines two new `alloc_mode` definitions in `cmm.mli` and `cmx_format.mli`, which can not be identical: we can not import `cmm.mli` in `cmx_format.mli` and we do not want to add too many definitions to `cmx_format.mli`. Surprisingly, we never need to convert between those two definitions. This distinction seems to occur already in `alloc_mode.mli`, where `For_applications` is always extracted to the `cmx_format` definition, while `For_allocations` is extracted to the cmm definition. To avoid adding extra dependencies, I moved these conversions to `to_cmm_shared.mli`.

Also note that this PR is against `main`, not `overwriting`, since there are no changes to the semantics.

2024-09-23 06:50 UTC, mshinwell commented
I'll review this, I don't think @goldfirere needs to.

2024-09-24 15:38 UTC, mshinwell requested changes

2024-09-24 15:38 UTC, mshinwell commented on backend/cmm.ml
> +  let print a =
This should be of type `Format.formatter -> t -> unit`, like so:
```ocaml
let print ppf t =
  match t with
  | Heap -> Format.fprintf ppf "Heap"
  ...
```

2024-09-24 15:38 UTC, mshinwell commented on backend/cmm.ml
> +  let equal a b =
We usually use `t1` and `t2` here, since these are of type `t`.

2024-09-24 15:38 UTC, mshinwell commented on backend/cfg/cfg_comballoc.ml
> +        | Cmm.Alloc_mode.Local -> return ()
I'm surprised you can't just write `Local` here - can you?

2024-09-24 15:38 UTC, mshinwell commented on backend/cfg/cfg_comballoc.ml
> +        | Cmm.Alloc_mode.Local -> return ()
There are various other occurrences of this elsewhere e.g. in `emit.mlp` - please omit the module path if possible.

2024-09-24 15:38 UTC, mshinwell commented on backend/cmm_helpers.ml
>  let alloc_boxedfloat32_header mode dbg =
For these I would just write `let alloc_boxedfloat32_header (mode : Cmm.Alloc_mode.t) dbg = ...` then you can omit all the module paths, which tend to clutter.

2024-09-24 15:38 UTC, mshinwell commented on backend/cmm_helpers.ml
> +    | Cmx_format.Alloc_heap -> ""
(Same here)

2024-09-24 15:38 UTC, mshinwell commented on file_formats/cmx_format.mli
> +type alloc_mode =
Maybe add a comment that this can't use `Cmm` because of a circular dependency.

2024-09-24 15:38 UTC, mshinwell commented on middle_end/flambda2/to_cmm/to_cmm_shared.ml
> +let alloc_mode_to_cmx t =
Maybe `alloc_mode_for_applications_to_cmx` would be clearer, and similarly for the other function below.

2024-09-24 20:26 UTC, anfelor commented
I have implemented all comments in my latest two commits.

2024-09-25 09:13 UTC, mshinwell approved these changes

2024-09-25 09:14 UTC, merged