Fix problems with allocation of stacks
ocaml-flambda/flambda-backend pull request #3153
Opened 2024-10-16 16:16 UTC by mshinwell

The existing code to allocate stacks, when stack checks are off, erroneously asks for memory not backed by huge pages on Linux.  In addition it can inhibit the transparent huge page coalescing algorithm (or split existing huge pages), because the page that gets `mprotect`ed might be in the middle of a proposed (or existing) huge page partially occupied by something else at an address just below the stack.  (We only consider 2Mb huge pages as this seems like the common case.)

This PR aims to fix these problems.  It also removes the use of `MAP_STACK`, as it seems that certain versions of the kernel might interpret this as a request to disable huge pages.

2024-10-16 16:33 UTC, stedolan commented
For the record, the reason I'm glad to get rid of `MAP_STACK` despite it being documented as a no-op is that in very recent kernel versions it's been changed to imply `VM_NOHUGEPAGE`: https://github.com/torvalds/linux/commit/c4608d1bf7c6536d1a3d233eb21e50678681564e

(Arguably you want your stacks to not be hugepages, because you generally don't use much of them. The trouble we've seen is that breaking hugepages for the stack affects adjacent heap areas, since the stack is often not 2MB aligned. Maybe we should investigate manually aligning these at some stage, but I definitely don't want the behaviour suddenly changing with kernel version upgrades)

2024-10-16 17:00 UTC, stedolan commented on ocaml/runtime/fiber.c
> +  struct stack_info* block = (struct stack_info*) (stack + extra_size);
It looks like you're throwing away the original `stack` value, which means the `munmap` in `caml_free_stack` isn't going to do the right thing.

2024-10-16 17:41 UTC, stedolan requested changes

2024-10-16 17:41 UTC, stedolan commented on ocaml/runtime/fiber.c
> +    caml_mem_unmap(block, len);
This needs to munmap `stack`, not `block`

2024-10-16 17:41 UTC, stedolan commented on ocaml/runtime/fiber.c
> +    caml_mem_unmap(mmap_base, stack->size);
Is stack->size right here?

2024-10-16 18:07 UTC, stedolan commented
This looks correct to me now (but it's late and I may have missed something).

Has it been tested? You can check what it's doing by looking at `/proc/self/smaps` before and after running a systhread.

2024-10-16 18:08 UTC, mshinwell commented
Will read this over and test tomorrow.

2024-10-23 15:53 UTC, stedolan commented
What testing has this had? In particular, does the current version have the right effect on mappings (as viewed by e.g. `smaps`) when threads are created/destroyed?

2024-10-24 10:40 UTC, mshinwell commented
This has been tested on a large multi-instance program with no crashes.  I also wrote a small program to inspect `smaps` before and after thread creation.  Here is an example of the situation after thread creation:
```
0x7fffb14f7000 = value returned by `caml_mem_map` for the thread stack

7fffb0cf7000-7fffb16f8000 rw-p 00000000 00:00 0
Size:              10244 kB
THPeligible:    1
7fffb16f8000-7fffb16f9000 ---p 00000000 00:00 0
Size:                  4 kB
THPeligible:    0
7fffb16f9000-7fffb56fa000 rw-p 00000000 00:00 0
Size:              65540 kB
THPeligible:    1
```
The value returned by `caml_mem_map` is in the middle of the first of these three mappings.  We can see that despite the presence of the guard page, the THP-eligibility of the first mapping (comprising something else's mapping at the lower addresses, followed by our unused 2Mb alignment mapping above that) is unaffected.

After this thread exited, the top mapping changed to:
```
7fffb0cf7000-7fffb14f7000 rw-p 00000000 00:00 0
Size:               8192 kB
```
We can see here that the value returned by `caml_mem_map` now forms the upper endpoint of this mapping, since our 2Mb unused alignment mapping has been unmapped.  The THP-eligibility of the `7fffb0cf7000` mapping remains unaffected.  The guard page mapping and the thread stack mapping itself have been freed.

2024-10-24 14:52 UTC, lpw25 approved these changes
Looks good to me

2024-10-24 14:53 UTC, merged

2024-10-27 18:14 UTC, stedolan reviewed
Looks good to me too!