Ensure that all pattern-matching-constants mode-cross uniqueness
ocaml-flambda/flambda-backend pull request #3272
Opened 2024-11-13 23:20 UTC by anfelor

This PR makes all constants mode-cross uniqueness. This is necessary since we can not really ensure that the switcher code that is generated for `Tpat_construct` correctly handles the case where projections may not be pushed down. 

I create a new `jkind` for `constant_data` which includes strings, boxed floats and boxed integers. A value of kind `constant_data` is equivalent to a value of kind `immutable_data` except that it crosses uniqueness. In the testsuite, I adjusted the tests for uniqueness where I now generate a list of functions (which will never mode-cross uniqueness and linearity) to avoid wrong test-results arising from mode-crossing.

2024-11-15 21:59 UTC, nmatschke requested changes
Though I can review the code, I feel ill-equipped to comment on whether this PR is a good idea.

First off, I do think `constant_data` vs `immutable_data` will be confusing for users, who mostly don't have the OCaml AST types burned into their brains. Even I was slightly surprised to be reminded that the language lets you match on `float`s, and I do a lot of PPX work!

But also, numbers I can sorta see, but `string` crossing uniqueness feels unintuitive to me. 

Is this our long-term solution to the problem, or something temporary until we can fix the code generation? I feel like I want someone else with a better understanding of our plans in this space to weigh in here.

2024-11-15 21:59 UTC, nmatschke commented on testsuite/tests/typing-layouts/jkinds.ml
> +val x : string t = {unique_field = "string"}
Should we have a new test demonstrating the error case here now?

2024-11-15 21:59 UTC, nmatschke commented on typing/typedtree.mli
> +   For the soundness for the uniqueness extension it is important that all
I don't have a great sense for how this compares to other similar kinds of things in the compiler, but I'd be worried that this comment isn't scary enough. "Btw you might cause miscompilation if you ignore this comment". And it's easy to miss in review, when someone adds a new constant, if the diff doesn't include it.

It's better to break the build when someone needs to update something. For example, perhaps some file somewhere could have a test like:
```ocaml
type crosses_uniqueness = I_remembered_to_make_this_cross_uniqueness

let _all_constants_mode_cross_uniqueness : Typedtree.constant -> crosses_uniqueness = function
  | Const_int _ -> I_remembered_to_make_this_cross_uniqueness
  | Const_char _ -> I_remembered_to_make_this_cross_uniqueness
  (* ... *)
  | Const_unboxed_nativeint _ -> I_remembered_to_make_this_cross_uniqueness
;;
```

Ideally there's already some kind of convention for this sort of thing the compiler.

2024-11-15 21:59 UTC, nmatschke commented on testsuite/tests/typing-unique/unique.ml
> +let inf2 (b : bool) (unique_ x : non_mode_cross) = unique_ let y = if b then x else [] in y
Iiuc `[]` should be coaliased someday, or something like that, so why not instead use `mk_non_mode_cross ()`?

2024-11-15 21:59 UTC, nmatschke commented on testsuite/tests/typing-unique/unique_analysis.ml
> +  | _, _ -> []
Same comment as in unique.ml re: just use `mk_non_mode_cross ()`.

2024-11-15 21:59 UTC, nmatschke commented on testsuite/tests/typing-unique/unique_analysis.ml
> +  | _, _ -> []
Same comment as in unique.ml re: just use `mk_non_mode_cross ()`.

2024-11-15 22:54 UTC, lpw25 commented
I don't thing we should be making these types cross uniqueness. Being able to reuse an int64 as another int64 is definitely valuable. What is particularly difficult about pattern matching on constants?

2024-11-17 09:26 UTC, lpw25 commented
If we think it will be a lot of work to get these patterns to have barriers associated with their operations, then it should be sufficient to just treat such patterns as uses of the associated values in the uniqueness analysis. For the types that do cross uniqueness that won't matter, and for the other types it will still be possible to do such pattern matching it will just require explicitly borrowing the value before matching on it.

2024-11-25 21:38 UTC, closed without merging