Supports mode annotation on function body
ocaml-flambda/flambda-backend pull request #3327
Opened 2024-11-29 14:42 UTC by riaqn

This PR adds the support for the following syntax:

```
let foo a b @ modes = ..
let foo a b : ty @@ modes = ..
fun a b @ modes -> ..
fun a b : ty @@ modes -> ..
```

Please do not merge until I finish the internal migration for the new parsetree.

2024-12-03 00:07 UTC, tdelvecchio-jsc requested changes
Liam to do further review since I realized I don't have context on typing/

2024-12-03 20:18 UTC, liam923 requested changes
(I did not review the changes in `parser.mly` under the premise that @tdelvecchio-jsc already reviewed it.)

I'd like to see a test that shows that this allows a stronger interface to be inferred for a `ml`-only module.

2024-12-03 20:18 UTC, liam923 commented on typing/untypeast.ml
> +                | Some (Texp_mode _) -> Misc.fatal_error "not supported Texp_mode"
Same question as above - I don't understand why this is an error

2024-12-06 17:10 UTC, riaqn commented on testsuite/tests/typing-modes/modes.ml
> +Error: This value escapes its region.
Yeah `local_` as the return mode of a function has a speical meaning: the function might allocate in caller's region. 
(It also contain the usual meaning that the returned value is local).

So the test in question should (ideally) be allowed due to mode crossing; but the example you give should continue to fail.

2024-12-06 17:10 UTC, riaqn commented on typing/untypeast.ml
> +    | Texp_mode _ -> Misc.fatal_error "not supported Texp_mode"
I'm a being a bit lazy here as I think `untypeast.ml` is never used.

2024-12-06 17:15 UTC, mshinwell commented on typing/untypeast.ml
> +    | Texp_mode _ -> Misc.fatal_error "not supported Texp_mode"
If so, should we delete it?

2024-12-06 17:20 UTC, liam923 commented on typing/untypeast.ml
> +    | Texp_mode _ -> Misc.fatal_error "not supported Texp_mode"
It's used in Merlin! So unfortunately I think we need to keep supporting it.

2024-12-06 17:20 UTC, riaqn commented on parsing/printast.ml
> +  modes i ppf ret_mode_annotations
I decided to simply not print `mode_annotations`, because that's duplicated by `vb_modes` already.

2024-12-10 14:56 UTC, liam923 approved these changes

2024-12-12 16:50 UTC, tdelvecchio-jsc approved these changes

2024-12-12 16:52 UTC, merged