Promote `val_modalities` to `Stable`
ocaml-flambda/flambda-backend pull request #3391
Opened 2024-12-18 16:26 UTC by riaqn

This PR promotes modalities on values descriptions and module declarations to `Stable`.

There are no longer behaviors controlled by `mode_alpha`, but maybe it's fine to keep it for future convenience.

I confirm that our internal code base builds without changes, with this PR.

2025-01-03 15:22 UTC, tdelvecchio-jsc approved these changes
Looks good.

2025-01-03 23:06 UTC, tdelvecchio-jsc requested changes
I'm currently running into an issue where
```
(* x.ml, with no mli *)
type t = T of unit

let t = T ()
let u = lazy t

(* y.ml *)
let _ @ uncontended = X.u

(* Error: This value is contended but expected to be uncontended. *)
```

I hypothesize (but have not checked) that this PR introduces this bug. Can you check?

2025-01-06 11:45 UTC, riaqn commented
This is #2967 missing a mode crossing spot. Will fix.

Since we will push `u` to stongest modality `portable`, that makes the implicit lazy closure `fun () -> t` portable, which makes `t` only available as `contended` in the closure, which makes the returns of the closure `contended` and thus the whole `lazy` is at `contended`.

2025-01-06 12:11 UTC, riaqn commented
Well I just realized that the said mode crossing is already there for general variable lookup. What's missing is that the kind system don't know `type t` crosses contention. You can either try #3284, or maybe manually specify that it crosses `contention`?

Do you encounter similiar issues where such `type t` contains mutable fields? That might be more tricky to think about.

2025-01-06 13:17 UTC, goldfirere requested changes
I think this should also update the documentation, now that we're putting the feature in stable.

2025-01-17 19:30 UTC, goldfirere approved these changes
Docs look fine. Is there an internal ticket to finish the job?

2025-01-22 22:25 UTC, merged

2025-01-23 09:29 UTC, riaqn commented
Yes internal JIRA-3903