updated cmm_helpers interface to be more amenable to adding other int sizes
ocaml-flambda/flambda-backend pull request #3415
Opened 2024-12-30 17:03 UTC by jvanburen

This is to prepare for adding small integer types
This just changes the interface - it doesn't really update any code.

The only code change is in `safe_div_bi`, instead of taking an integer size, it explicitly takes an optional flag that tells us whether division could overflow. This is not only more clear, but the function is only used in a couple places so it's easy to verify that the new behavior is correct.

2025-01-02 13:52 UTC, Gbury commented on backend/cmm_helpers.ml
> +   occur, in which case we force x / -1 = -x and x mod -1 = 0. (PR#5513). *)
maybe add in a comment that the specified behavior is reached via the `mkop` and `mkm1` functions, which are used to build the correct cmm expressions respectively  in the usual case, and in the case where the divisor is `-1` (and the arch crashes on overflow).

2025-01-02 13:52 UTC, Gbury commented on backend/cmm_helpers.ml
> +let safe_div_bi =
I wouldn't mind an eta-expension here for clarity (and it might also be generate slightly better code though that's not a real concern here I'd say).

2025-01-02 13:52 UTC, Gbury commented on backend/cmm_helpers.ml
> +let safe_mod_bi = safe_divmod_bi mod_int (fun _ dbg -> Cconst_int (0, dbg))
same as remark for the eta-expansion

2025-01-02 13:52 UTC, Gbury commented on backend/cmm_helpers.ml
> +  if bits = 0 then e else ignore_low_bit_int e
why not check that `bits` here is 1, as is done for the `zero_extend` and `sign_extend` functions ? I agree that the implementation is technically correct, since this is only used for optimizations, and thus "ignoring" less bits than requested is not wrong, but still, it would maybe be better in this iteration to check that we only ever ignore one bit ?

2025-01-02 13:52 UTC, Gbury commented on backend/cmm_helpers.mli
> +val sign_extend : bits:int -> dbg:Debuginfo.t -> expression -> expression
missing doc comment here and for `zero_extend` (especially considering that the "old" functions had doc comments)

2025-01-02 13:52 UTC, Gbury commented on backend/cmm_helpers.mli
> +    first argument by. *)
maybe also specify that the result is tagged ?

2025-01-02 13:52 UTC, Gbury commented on backend/cmm_helpers.mli
> +    blocks} [immediate_or_pointer] is not needed as the layout is implied from the name,
maybe add full break lines (including a white line so that ocamlformat doesn't break everything) so that the doc title (in brackets) is more distinguishable from the explanation text ?

2025-01-02 13:52 UTC, Gbury commented on backend/cmm_helpers.mli
> +    assigned without caml_modify (etc.). *)
Even though i understand who you reached this point, it'as a bit weird to specify why these function do not take some arguments (all the more since you don't specify the arguments they do take).

2025-01-02 13:52 UTC, Gbury commented on middle_end/flambda2/to_cmm/to_cmm_primitive.ml
> +      | Naked_int64 | Naked_nativeint -> Word_int
this code could be factored out into a function from the `field_kind` to the `memory_chunk` and used for both the `get` and `set` primitives.

2025-01-15 17:07 UTC, Gbury requested changes

2025-01-15 17:07 UTC, Gbury commented on backend/cmm_helpers.mli
> +    ake as first argument a tagged caml integer, and as
```suggestion
    Take as first argument a tagged caml integer, and as
```

2025-01-15 17:07 UTC, Gbury commented on backend/cmm_helpers.mli
> +    needed as the layout is implied from the name, and [initialization_or_assignment] is
the layout is not implied from the name anymore, but rather by the `memory_chunk` given as argument

2025-01-15 17:07 UTC, Gbury commented on utils/misc.mli
> +    if [n] is a power of 2*)
this is quite an under-specification (technically, the doc says nothing about the returned value if the input is not a power of 2, although I'm relatively certain the function is used on such arguments....), but since the other functions have the same style of doc, I guess it's okay-ish ?

2025-01-16 17:58 UTC, jvanburen commented on backend/cmm_helpers.ml
> +          dbg
to be honest, I don't actually know :disappointed: I'm preserving the behavior from before.

2025-01-17 14:45 UTC, Gbury requested changes

2025-01-17 14:45 UTC, Gbury commented on backend/cmm_helpers.ml
> +  | x, Ctuple [] -> x
I'm not sure this is correct: consider for instance something along the lines of `sequence (const_int 0) (Ctuple [])` (whose semantics is dubious, but still), this line would change the "result" of the cmm expression.

For what it's worth, I sure hope that we do not produce such expressions (whose semantics and usefulness is relatively unclear), and therefore this should not matter, but I'd rather remove this unless you have a compelling argument.

2025-01-17 14:45 UTC, Gbury commented on backend/cmm_helpers.ml
> +           against min_int. *)
So, this relies on the fact that comparisons are expected to return `0` or `1` for `false` and `true` resp. right ? this would be useful to document somewhere (let's say `cmm.ml` or `cmm.mli`), since even if we assume C-like conventions I think that the only requirements is `0` for false and anything else for `true` (which someone may be tempted to use at one point for some optimization).

2025-01-17 14:45 UTC, Gbury commented on backend/cmm_helpers.ml
> +          dbg
oh apologies, because of all of the re-ordering (and replacing substractions from zero with negation) I missed that this was not an actual change. I guess it's okay for now, though if you have time to dive into this and find out why, I wouldn't object to some documentation of why it's done like that, ^^

2025-01-17 14:45 UTC, Gbury commented on backend/cmm_helpers.ml
> +      let l = Misc.log2_nativeint divisor in
`log2_nativeint n` works correctly if `n > 0` according to its doc (and I admit that I don't have the motivation to check it works for negative integers right now, or what would be the exact spec), but with the new code, this is not guaranteed for `divisor` anymore here (at least not obviously like before), unless `is_power_of_2` also ensures that its argument is positive, in which case it might be useful to either make it part of the function name, or at least put a remainder in comments here.

2025-01-17 14:45 UTC, Gbury commented on backend/cmm_helpers.ml
>           res = t + sign-bit(c1) *)
you should update the algorithm to:
- match the new names below (particular the renamings such as `t -> q`, `c1 -> n`)
- make the algorithm reflect what is actually computed now as there are a few new cases (related to the handling of negative dividends if I'm not mistaken)

2025-01-17 19:15 UTC, jvanburen commented on backend/cmm_helpers.ml
> +          dbg
It's because the original author didn't implement the signed division algorithm from the reference they cite, they only implmented unsigned division optimization. I'll add a comment.

2025-01-17 19:20 UTC, jvanburen commented on backend/cmm_helpers.ml
> +  | x, Ctuple [] -> x
Unless i'm mistaken, the previous code had this issue too, no?
```
let sequence x y =
  match x, y with
  | Ctuple [], _ -> y
  | _, Ctuple [] -> x
  | _, _ -> Csequence (x, y)

```

2025-01-17 19:38 UTC, Gbury commented on backend/cmm_helpers.ml
> +  | x, Ctuple [] -> x
indeed, and it probably means that this particular part of code is likely unused in practice, but since we're touching it, it makes sense to fix it

2025-01-17 19:45 UTC, jvanburen commented on backend/cmm_helpers.ml
> +  | x, Ctuple [] -> x
I changed it back and used bind instead

2025-01-17 19:46 UTC, jvanburen commented on backend/cmm_helpers.ml
> +           against min_int. *)
I can just use an if statement and rely on it getting optimized later

2025-01-17 20:34 UTC, jvanburen commented on backend/cmm_helpers.ml
> +      let l = Misc.log2_nativeint divisor in
i added a comment - this is only ever called on positive powers of 2 where it clearly works

2025-01-20 16:08 UTC, Gbury commented on backend/cmm_helpers.ml
> +         min_int (the only negative power of 2).
this comment is probably misplaced, given that this section of code deals with `n = min_int` (and `n` is `[divisor]` unless I'm mistaken) which is usually negative. This should instead be a few lines below.

2025-01-20 16:12 UTC, Gbury commented on testsuite/tests/basic/division_by_constant.ml
> +let[@inline always] [@specialise always] check ~divisor =
please use two different names for the `check` functions (e.g. `check_one` and `check` ?)

2025-01-20 16:13 UTC, Gbury commented on testsuite/tests/basic/division_by_constant.ml
> +    (Sys.opaque_identity check)
No need for the `Sys.opaque_identity`, considering `check` is already `[@inline never]`

2025-01-20 16:15 UTC, Gbury commented on testsuite/tests/basic/division_by_constant.ml
> +let[@inline always] [@specialise always] check ~divisor =
also, you can remove the `[@specialise always]` which should be useless/redundant given that the function is `[@inline always]` (also, specialisation is not yet done by flambda2 anyways for now...)

2025-01-20 16:20 UTC, Gbury commented on testsuite/tests/basic/division_by_constant.ml
> +let () = check ~divisor:(-3n)
from what I read in Hacker's delight, `5` and `7` seem to also be good candidates for manual testing

2025-01-20 16:24 UTC, Gbury commented on testsuite/tests/basic/division_by_constant.ml
> +   replaced *)
this comment is quite confusing:
- you could specify that it was generated by a manual run of the `test_cases` function to have a hard-coded list of semi-random numbers (whereas all divisors are tested on the list generated by `test_cases`)
- the comment about `check` being inlined also applies to the "manual" tests above, so stating it here is confusing. You should instead add a comment to this effect on the definition of the `check` function explaining how the `[@inline]` annotations are used to ensure that the divisor is a compile-time known constant but not the dividend. That would also help specify exactly what is being tested by this file.

2025-01-20 16:32 UTC, Gbury commented on testsuite/tests/basic/division_by_constant.ml
> +let () = check ~divisor:(-3n)
also, `1`, `-1`, `min_int` seems like good candidates since they have special code paths in the compiler.

In the same vein of interesting edge cases, we also have `max_int`, and `0` (which may be slightly more complex to check since it raises, but a good test nonetheless).

Lastly, you could add a few manual tests where the dividend and/or divisor expressions have side-effects (e.g. `((fun x -> (print_endline "foo"; x) / (print_endline "bar"; 3))[@inlined never]) 42`

2025-02-04 16:14 UTC, Gbury approved these changes

2025-02-04 17:14 UTC, merged