Add code coverage using bisect_ppx
ocaml-flambda/flambda-backend pull request #352
Opened 2021-10-26 16:08 UTC by lukemaurer

Coverage is enabled by passing `--enable-coverage` to `./configure`. It's intended that mostly only CI builds will use it, since only the boot compiler can be built (which suffices for running tests).

2021-11-25 17:57 UTC, lukemaurer commented
Marking as a draft while I work on fixing the build failure with coverage enabled.

2022-01-05 15:31 UTC, Gbury commented
With coverage enable, you seem to skip the stage2 build. In that situation, is it possible to run the testsuite ? (since at the end of stage1, we haven't yet build an flambda2-compatible stdlib)

2022-05-04 17:00 UTC, lukemaurer commented
> With coverage enable, you seem to skip the stage2 build. In that situation, is it possible to run the testsuite ? (since at the end of stage1, we haven't yet build an flambda2-compatible stdlib)

Not the upstream testsuite, but we can run all (well, both) of our tests.

2022-05-04 17:02 UTC, lukemaurer commented
Converting to draft. There seems to be a bug in `bisect-ppx-report` that stops `bisect-ppx-report html` as soon as it sees a subdirectory.

2022-05-24 12:28 UTC, mshinwell requested changes
I think this looks good except for a couple of minor comments.  We can make incremental fixes if something's wrong.

2022-05-24 12:28 UTC, mshinwell commented on Makefile
> +	ocaml_subdirs_to_ignore=otherlibs
Weird indentation

2022-05-24 12:28 UTC, mshinwell commented on .github/workflows/coverage.yml
> +    - name: Publish coverage report
Where exactly does the report end up?

2022-05-26 11:31 UTC, mshinwell commented on .github/workflows/coverage.yml
> +    - name: Publish coverage report
The answer turns out to be in an "artifacts" place associated with Github Actions.

2022-05-26 11:53 UTC, mshinwell approved these changes

2022-05-26 11:57 UTC, merged