Disconnect blocks with exceptional successors
ocaml-flambda/flambda-backend pull request #49
Opened 2021-06-10 14:02 UTC by xclerc

We currently only allow the disconnection of empty blocks with
no more than one successor. It seems safe, however, to *not* take
into account exceptional successors when we perform the check.

This pull request does exactly that, but ensures that the set of
predecessors of any exceptional successor is properly updated.

2021-06-11 15:43 UTC, gretay-js commented
I think this PR is technically correct, but I do not understand what code would trigger the situation in which it applies.

In Disconnect_blocks, we don't check that the block is empty before disconnecting it. 

If the block is a fallthough (i.e., Disconnect_block.disconnect is called from fallthrough elimination), then it is empty and therefore should have exactly one "normal" successor and no exceptional successors.
If the block is dead (i.e. Disconnect_block.disconnect is called from dead code elimination) then the block might not be empty, but it does not have any predecessors, and so there is no restriction on the number of successors.

How do we get a CFG with an empty block that is not dead and has a single "normal" successor and at least one exceptional successor?

2021-06-11 15:50 UTC, xclerc commented
The in-progress translation from `Mach.fundecl` to a graph
can sometimes generate an empty block which happens to
have an exceptional successor. Fallthrough block elimination
then fails, and I don't think there is a good reason for that:
since the block is empty and ends with an `Always _`, it can
never raise and the exceptional successor is inconsequential.

2021-06-11 17:14 UTC, gretay-js requested changes
Ok, thanks for the explanation. It's fine to temporarily break the invariant "a block that cannot raise does not have any exceptional successors" if it simplifies the translation from Mach to Cfg, and then clean up the graph using fallthrough elimination. 

I think this part is not right:
https://github.com/ocaml-flambda/flambda-backend/blob/3b5b205ee95f1aed09525ba733c560fadbd3d28b/backend/cfg/disconnect_block.ml#L57-L67

Handle exceptional successors separately, and don't do the union with `block.predecessors` (line 66) for them, only drop the `label` of the disconnected block from their predecessors:
```
succ_block.predecessors <-  Label.Set.remove label succ_block.predecessors
```

2021-06-22 10:20 UTC, xclerc commented
I am a bit confused, because the definition of `successors` has
not changed but has only been moved. Granted, the condition to
evaluate `Misc.fatal_errorf` has changed, but it looks like the
code you point as problematic was already reachable with a block
terminated with `Never` and an exceptional successor.

2021-06-22 12:35 UTC, gretay-js commented
> it looks like the code you point as problematic was already reachable with a block
> terminated with `Never` and an exceptional successor.

You are absolutely right, the current version is also broken for disconnecting a block with one exceptional successor and some predecessors.  Disconnect_block is never called for such blocks from Eliminate_fallthrough:
https://github.com/ocaml-flambda/flambda-backend/blob/3b5b205ee95f1aed09525ba733c560fadbd3d28b/backend/cfg/eliminate_fallthrough_blocks.ml#L34-L37

2021-06-23 09:08 UTC, gretay-js approved these changes
Look good, thank you!

2021-06-23 10:55 UTC, merged