Review of To_cmm_primitive
ocaml-flambda/flambda-backend pull request #680
Opened 2022-06-06 14:51 UTC by mshinwell

Best read commit by commit.

@xclerc is going to look at the `Naked_immediate` cases, some of which appear to be wrong (a couple of them would have triggered `assert false`, indeed).

There is an open question as to whether 32-bit string loads should be sign extended.  It seems that the `Cmmgen` code doesn't do this, unless I misread it, and the `bytes.ml` implementation doesn't contain sign extensions (unlike in the 8 and 16 bit cases).  I wonder if this might be a bug in `Cmmgen`.

2022-06-13 16:01 UTC, Gbury requested changes
I left a few comments, but overall I think the main thing to do is to properly trat `Naked_immediate` as a nativeint minus one bit, the same way `Naked_Int32` is a nativeint minus 32 bits. However, while doing that we must make sure that doesn't introduce any unnecessary operations (particularly when producing code for arithmetic operations from source ocaml code on tagged integers).

2022-07-04 10:37 UTC, mshinwell commented on middle_end/flambda2/to_cmm/to_cmm_primitive.ml
> +  | Naked_int64, Swap_byte_endianness -> C.bbswap Pint64 arg dbg
I'm going to delete these cases in a subsequent PR.

2022-07-04 10:40 UTC, mshinwell commented on middle_end/flambda2/to_cmm/to_cmm_primitive.ml
> +    (* XXX this is wrong for Naked_immediate ("TBD" case also needs fixing
`Naked_immediate` changes are in #696.

2022-07-04 10:44 UTC, mshinwell commented on middle_end/flambda2/to_cmm/to_cmm_primitive.ml
> +  (* XXX wrong for Naked_immediate *)
`Naked_immediate` changes are on #696.

2022-07-04 10:45 UTC, mshinwell commented on middle_end/flambda2/to_cmm/to_cmm_primitive.ml
>  let binary_int_comp_primitive _env dbg kind signed cmp x y =
Fixed

2022-07-04 10:45 UTC, mshinwell commented on middle_end/flambda2/to_cmm/to_cmm_primitive.ml
> +    (* XXX check if this is right for Naked_immediate *)
`Naked_immediate` changes are on #696.

2022-07-04 10:49 UTC, mshinwell commented on middle_end/flambda2/to_cmm/to_cmm_primitive.ml
> +    (* XXX Is this correct? mshinwell had an old note saying that this case
Let's deal with this on #696.

2022-07-04 10:54 UTC, mshinwell commented on middle_end/flambda2/to_cmm/to_cmm_primitive.ml
> +    (* XXX is this correct for Naked_immediate? *)
I've fixed `Neg` for `Naked_int32`.  For `Naked_immediate` let's move to #696.

2022-07-04 10:55 UTC, mshinwell commented on middle_end/flambda2/to_cmm/to_cmm_primitive.ml
> +    (* XXX check if this is right for Naked_immediate *)
Also: `Naked_immediate` isn't used much.  The first aim must be to get a correct implementation; any optimisation can be left until later.

2022-07-04 10:57 UTC, mshinwell commented on middle_end/flambda2/to_cmm/to_cmm_primitive.ml
`Naked_immediate` discussions on #696 please.

2022-07-04 10:58 UTC, mshinwell commented on middle_end/flambda2/to_cmm/to_cmm_primitive.ml
>      None, C.sign_extend_32 dbg (C.untag_int arg dbg)
I've added this as a `CR-someday`.

2022-07-04 11:25 UTC, gretay-js approved these changes

2022-07-04 13:59 UTC, merged