Add a `returns` field to `Cmm.Cextcall`
ocaml-flambda/flambda-backend pull request #74
Opened 2021-07-01 16:07 UTC by xclerc

This pull request imports / rebases ocaml-flambda/ocaml#168,
which is part of the tip of https://github.com/ocaml-flambda/ocaml.

(This pull request depends on #72.)

(This pull request is expected to be equivalent to #67.)

2021-07-15 16:04 UTC, xclerc commented
I have reviewed these changes and believe they are correct.
However, given the number of conflicts between the two
versions, it might be better to have another review of https://github.com/ocaml-flambda/flambda-backend/pull/74/commits/53ccf9e98ca5040a4ec55cebef0519dc6b8d0918.

2021-07-16 09:19 UTC, gretay-js reviewed
It looks fine, I just have a couple of minor comments.

Just to confirm: this PR just only adds the `returns` field, and not all the changes in https://github.com/ocaml-flambda/ocaml/pull/168, right? In particular, there are 3 commits in this PR but the last one (the merge https://github.com/ocaml-flambda/flambda-backend/pull/74/commits/cc895d93bd891828c5debf22cb874f2edc42ca9d) seems to have removed the changes made by the first (CMM traps https://github.com/ocaml-flambda/flambda-backend/pull/74/commits/cc895d93bd891828c5debf22cb874f2edc42ca9d).

2021-07-16 09:19 UTC, gretay-js commented on backend/cmmgen.ml
> +     args, dbg))
This change is not related (it probably snack in from a previous issue with rebase, fixed in https://github.com/ocaml-flambda/flambda-backend/pull/79).
Please revert it to invoke `cextcall` as before and pass `true` for the new `returns` argument.

2021-07-16 09:19 UTC, gretay-js commented on backend/debug/available_regs.ml
> +      | Itrywith (_body, Delayed _nfail, _handler) ->
I am not sure why this change is here.

2021-07-16 09:19 UTC, gretay-js commented on backend/printcmm.ml
> +      | Cextcall { ty; ty_args; alloc = _; func = _; } ->
Should we print the value of returns when it's false?

2021-07-16 09:19 UTC, gretay-js commented on ocaml/testsuite/tools/parsecmm.mly
> +               {Cop(Cextcall {func=$3; ty=$5; alloc=false;
This file shouldn't change because we haven't changed `ocaml/asmcomp/cmm.ml` or running asmgen gets from ocaml subdirectory will fail.

2021-07-16 09:22 UTC, gretay-js requested changes
Above comment was supposed to  be "Request changes" (defeated by github review interface)

2021-07-16 11:03 UTC, gretay-js approved these changes
Thanks for fixing it! The change in parsecmm under `ocaml` was a mistake by an earlier commit, I'll fix it in a separate PR.

2021-07-16 11:04 UTC, merged