Intrinsics for clz and ctz with non-zero argument
ocaml-flambda/flambda-backend pull request #75
Opened 2021-07-02 10:47 UTC by gretay-js

Add variants of CLZ and CTZ operations on Int64, Int32, and Nativeint that assume that the argument of is non-zero, and do not emit conditional branches around BSR and BSF instructions.

2021-07-16 13:06 UTC, mshinwell requested changes

2021-07-16 13:06 UTC, mshinwell commented on backend/cmm_helpers.ml
> +       always set the corresponding field to [true]. *)
This comment just says what the code says.  Let's change it to say what the reason is...

2021-07-16 13:22 UTC, gretay-js commented on backend/cmm_helpers.ml
> +       because we make it non-zero below by setting bit 32. *)
Is it better?

2021-07-21 10:44 UTC, mshinwell commented on backend/cmm_helpers.ml
> +       because we make it non-zero below by setting bit 32. *)
Yes!

2021-07-21 10:45 UTC, mshinwell approved these changes

2021-07-21 10:46 UTC, merged