Port ocaml/ocaml#11727 and ocaml/ocaml#11732
ocaml-flambda/flambda-backend pull request #965
Opened 2022-11-17 13:30 UTC by stedolan

Two small type system fixes for first-class module issues in 4.14 (reviewed upstream)

2022-11-17 17:35 UTC, antalsz requested changes
You missed a comment we should bring in, and you could also bring in the `Changes` update if you wanted; happy to merge after you do #1 (and #2 if you want to)

2022-11-17 17:35 UTC, antalsz commented on ocaml/typing/typemod.ml
>    package_constraints env loc (Mty_ident p)
Please bring in the comment here, too!

2022-11-17 17:38 UTC, stedolan commented on ocaml/typing/typemod.ml
>    package_constraints env loc (Mty_ident p)
Done

2022-11-17 17:38 UTC, antalsz approved these changes

2022-11-17 17:38 UTC, stedolan commented
I generally don't bother porting edits to Changes to flambda-backend, since it's not read by users of this repo and it's a constant source of merge conflicts if we try to update it.

2022-11-18 10:36 UTC, lpw25 approved these changes

2022-11-18 10:43 UTC, merged