Missing warnings for @inlined attributes in classic mode
ocaml-flambda/flambda-backend pull request #972
Opened 2022-11-22 14:31 UTC by lthls

(@Keryan-dev please review when you have some time -- I may have missed a few cases)

2022-11-22 14:33 UTC, lthls commented
Note: Closure has a distinction between unknown functions and functions with no information, but to do it in classic mode we would need a bit of refactoring so I've left it out.
There's no warning for ignored `@inline` attributes, but this matches Closure.

2022-11-23 13:46 UTC, Keryan-dev reviewed
Looks fine. I put a CR somewhere saying warnings are missing that can be decommissioned.

2022-11-23 13:54 UTC, Keryan-dev approved these changes

2022-11-23 13:55 UTC, mshinwell commented
This isn't quite right yet, as discussed

2023-01-09 12:04 UTC, mshinwell commented
@lthls what's the status of this one?

2023-01-09 12:47 UTC, lthls commented
I don't remember exactly what we discussed. This PR should get warnings in the right places, but I'm not sure we'll consistently get the exact same warnings as either Closure or Simplify. So if there are tests that check the exact warning string (and I suspect there are in the testsuite), we might fail those in classic mode.

2023-02-23 17:08 UTC, mshinwell commented
@lthls maybe we should rebase and merge this?  If the warnings are slightly different it should be ok, and we can iterate anyway.

2023-03-28 13:08 UTC, Gbury requested changes
This looks good (modulo the unroll/unrolled comment), and it adds a warning on partial applications which is currently missing, but for partial applications, we should also remove the attribute, else Simplify will emit another warning about unknown function information (which is extremely confusing).

2023-03-28 13:08 UTC, Gbury commented on middle_end/flambda2/simplify_shared/inlining_helpers.ml
> +let string_of_kind = function Inlined -> "[@inlined]" | Unroll -> "[@unroll]]"
```suggestion
let string_of_kind = function Inlined -> "[@inlined]" | Unroll -> "[@unrolled]]"
```

Only the `[@unrolled <n>]` annotation exists (cf the flambda manual : https://v2.ocaml.org/manual/flambda.html#s%3Aflambda-manual-control ).

2023-03-28 13:08 UTC, Gbury commented on middle_end/flambda2/simplify_shared/inlining_helpers.ml
> +  | Unroll
```suggestion
  | Unrolled
```

As said in another comment, we only have "unrolled", not "unroll"

2023-03-28 13:24 UTC, lthls commented
I've fixed the names and tweaked the partial application stub to remove the inlining attributes from the original application.
I think that issue #1261 will be fixed by this PR (at least the error messages on the sample program look coherent).

2023-03-28 14:35 UTC, merged